server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 2048

spring:
  application:
    name: waveguide-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/waveguide_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    show-sql: true

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET:veryLongAndSecretKeyThatNoOneWillEverGuessEvenIfTheyTryHardForALongTimeAndItShouldBeAtLeast256BitsLong}
      expiration-ms: 86400000  # 24 hours
      issuer: waveguide-management-system
    bcrypt:
      strength: 12
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
  rate-limiting:
    requests-per-hour: 100

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    com.waveguide: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/waveguide-management-system.log
    max-size: 10MB
    max-history: 7

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  packages-to-scan: com.waveguide.controller